ConnectionBDBundle\Entity\Biofilme:
    type: entity
    table: biofilme
    indexes:
        diente_biofilme_idx:
            columns:
                - idDiente
    id:
        posicion:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        placa:
            type: boolean
            nullable: true
        fecha:
            type: date
            nullable: true
    manyToOne:
        iddiente:
            targetEntity: Diente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idDiente:
                    referencedColumnName: idDiente
            orphanRemoval: false
    lifecycleCallbacks: {  }
