ConnectionBDBundle\Entity\Diente:
    type: entity
    table: diente
    indexes:
        dentadura_diente_idx:
            columns:
                - idDentadura
    id:
        iddiente:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idDiente
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            fixed: false
        existencia:
            type: boolean
            nullable: false
        tipo:
            type: integer
            nullable: false
            unsigned: false
    manyToOne:
        iddentadura:
            targetEntity: Dentadura
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idDentadura:
                    referencedColumnName: idDentandura
            orphanRemoval: false
    lifecycleCallbacks: {  }
