ConnectionBDBundle\Entity\Expediente:
    type: entity
    table: expediente
    indexes:
        paciente_expediente_idx:
            columns:
                - idPaciente
    id:
        idexpediente:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idExpediente
            generator:
                strategy: IDENTITY
    manyToOne:
        idpaciente:
            targetEntity: Paciente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idPaciente:
                    referencedColumnName: cedula
            orphanRemoval: false
    lifecycleCallbacks: {  }
