ConnectionBDBundle\Entity\TratamientoGeneral:
    type: entity
    table: tratamiento_general
    id:
        idgeneral:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idGeneral
            generator:
                strategy: IDENTITY
    fields:
        nombreTratamiento:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: nombre_tratamiento
        descripcion:
            type: string
            nullable: true
            length: 200
            fixed: false
    lifecycleCallbacks: {  }
